-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- PRODUCTS TABLE
create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  sku text unique not null,
  category text,
  fabric_type text,
  base_price numeric(10, 2) not null,
  image_url text,
  availability text default 'In Stock',
  stock_level integer default 0,
  description text,
  specifications jsonb default '{}'::jsonb,
  sizes text[] default '{}',
  colors text[] default '{}',
  production_time text,
  minimum_order integer default 1,
  is_new boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for products
alter table public.products enable row level security;

-- Create policy to allow read access to everyone
create policy "Enable read access for all users" on public.products
  for select using (true);

-- Create policy to allow insert/update/delete for authenticated users only
create policy "Enable write access for authenticated users only" on public.products
  for all using (auth.role() = 'authenticated');


-- ORDERS TABLE
create table public.orders (
  id uuid default uuid_generate_v4() primary key,
  order_number text unique not null,
  customer_name text not null,
  customer_email text,
  product_id bigint references public.products(id),
  product_name text, -- De-normalized for easier display if product is deleted
  design_notes text,
  quantity integer not null,
  unit_price numeric(10, 2),
  total_amount numeric(10, 2),
  status text default 'pending', -- pending, in_production, quality_check, shipped, completed
  priority text default 'medium',
  order_date date default try_cast(now() as date),
  due_date date,
  production_line text,
  assigned_to text,
  progress integer default 0,
  specifications text,
  timeline jsonb default '[]'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS for orders
alter table public.orders enable row level security;

-- Create policy to allow read access for authenticated users
create policy "Enable read access for authenticated users" on public.orders
  for select using (auth.role() = 'authenticated');

-- Create policy to allow all actions for authenticated users
create policy "Enable write access for authenticated users" on public.orders
  for all using (auth.role() = 'authenticated');

-- SEED DATA (Optional - Run if you want initial data)
-- Insert Products
insert into public.products (name, sku, category, fabric_type, base_price, image_url, availability, stock_level, description, specifications, sizes, colors, production_time, minimum_order, is_new)
values
  ('Classic Cotton Crew Neck', 'CCN-001', 'Basic', '100% Cotton', 12.99, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400', 'In Stock', 250, 'Premium quality crew neck t-shirt.', '{"weight": "180 GSM", "fit": "Regular", "neckline": "Crew Neck", "sleeves": "Short Sleeve"}', ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['White', 'Black', 'Navy', 'Gray', 'Red'], '3-5 days', 50, true),
  ('Premium V-Neck Tee', 'PVN-002', 'Premium', 'Cotton Blend', 18.50, 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400', 'Low Stock', 45, 'Sophisticated v-neck t-shirt.', '{"weight": "200 GSM", "fit": "Slim Fit", "neckline": "V-Neck", "sleeves": "Short Sleeve"}', ARRAY['S', 'M', 'L', 'XL', 'XXL'], ARRAY['White', 'Black', 'Charcoal', 'Navy', 'Burgundy'], '5-7 days', 25, false),
  ('Athletic Performance Tee', 'APT-003', 'Athletic', 'Polyester Blend', 22.00, 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400', 'In Stock', 180, 'High-performance athletic t-shirt.', '{"weight": "150 GSM", "fit": "Athletic Fit", "neckline": "Crew Neck", "sleeves": "Short Sleeve"}', ARRAY['XS', 'S', 'M', 'L', 'XL', 'XXL'], ARRAY['Black', 'Navy', 'Royal Blue', 'Red', 'Green'], '4-6 days', 30, true);

